version: '3.8'

services:
  subtensor:
    profiles:
      - localnet
    build:
      context: .
      dockerfile: .docker/subtensor/Dockerfile
    restart: unless-stopped

  subtensor_setup:
    profiles:
      - localnet
    depends_on:
      - subtensor
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "utils/init_solochain.py"]

  miner_server:
    environment:
      - MINER_HOST=${MINER_HOST}
      - MINER_PORT=${MINER_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "blackbox_example/miner_server.py"]

  validator_server:
    environment:
      - VALIDATOR_HOST=${VALIDATOR_HOST}
      - VALIDATOR_PORT=${VALIDATOR_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "blackbox_example/validator_server.py"]

  miner:
    depends_on:
      - miner_server
      - validator_server
    environment:
      - MINER_NAME=${MINER_NAME}
      - MINER_HOTKEY=${MINER_HOTKEY}
      - NETWORK_TYPE=${NETWORK_TYPE}
      - CHAIN_ENDPOINT=${CHAIN_ENDPOINT}
      - NETWORK_UID=${NETWORK_UID}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "neurons/miner.py", "--netuid",  "222", "--wallet.name", MINER_NAME, "--wallet.hotkey", MINER_HOTKEY, "--subtensor.network", NETWORK_TYPE]

  validator:
    depends_on:
      - miner_server
      - validator_server
      - miner
    environment:
      - VALIDATOR_NAME=${VALIDATOR_NAME}
      - VALIDATOR_HOTKEY=${VALIDATOR_HOTKEY}
      - NETWORK_TYPE=${NETWORK_TYPE}
      - CHAIN_ENDPOINT=${CHAIN_ENDPOINT}
      - NETWORK_UID=${NETWORK_UID}
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "neurons/validator.py", "--netuid", "222", "--wallet.name", VALIDATOR_NAME, "--wallet.hotkey", VALIDATOR_HOTKEY, "--subtensor.network", NETWORK_TYPE]
networks:
  chainnet:
    driver: bridge