services:
  miner_server_openai:
    build:
      context: .
      dockerfile: Dockerfile
    image: miner_server_openai
    container_name: miner_server_openai
    command: python model_servers/miner_server_open_ai.py
    environment:
      SERVER_PORT: 5000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - solidity-audit

  miner_server_corcel:
    build:
      context: .
      dockerfile: Dockerfile
    image: miner_server_corcel
    container_name: miner_server_corcel
    command: python model_servers/miner_server_corcel.py
    environment:
      SERVER_PORT: 5000
      CORCEL_API_KEY: ${CORCEL_API_KEY}
      CORCEL_MODEL: 'llama-3-1-70b'
      MAX_TRIES: 3
    restart: unless-stopped
    networks:
      - solidity-audit

  miner:
    build:
      context: .
      dockerfile: Dockerfile
    image: miner
    container_name: miner
    environment:
      MNEMONIC_COLDKEY: ${MINER_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${MINER_HOTKEY_MNEMONIC}
      WALLET_NAME: miner
      WALLET_HOTKEY: default
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ${NETWORK_TYPE}
      CHAIN_ENDPOINT: ${CHAIN_ENDPOINT}
      WORKER_TYPE: 'miner'
      EXTERNAL_IP: ${EXTERNAL_IP}
      MINER_SERVER: 'http://miner_server_corcel:5000'
      BT_AXON_PORT: 8091
      COLDKEY_DESCRIPTION: ''
    ports:
      - 8091:8091
    restart: unless-stopped
    networks:
      - solidity-audit

  validator:
    build:
      context: .
      dockerfile: Dockerfile
    image: validator
    container_name: validator
    environment:
      MNEMONIC_COLDKEY: ${VALIDATOR_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${VALIDATOR_HOTKEY_MNEMONIC}
      WALLET_NAME: validator
      WALLET_HOTKEY: default
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ${NETWORK_TYPE}
      CHAIN_ENDPOINT: ${CHAIN_ENDPOINT}
      WORKER_TYPE: 'validator'
      BT_AXON_PORT: 8100
      COLDKEY_DESCRIPTION: ''
      VALIDATOR_TIME: ${VALIDATOR_TIME}
    restart: unless-stopped
    networks:
      - solidity-audit

networks:
  solidity-audit:


