services:
  subtensor_localnet:
    build:
      context: ..
      dockerfile: .localnet/Dockerfile
      args:
        BRANCH: v1.1.6
    container_name: subtensor_localnet
    ports:
      - 9946:9946
    restart: unless-stopped
