version: '3.8'

services:
  subtensor:
    networks:
      - chainnet
    build:
      context: ..
      dockerfile: .docker/subtensor/Dockerfile
    restart: unless-stopped

  subtensor_setup:
    networks:
      - chainnet
    depends_on:
      - subtensor
    environment:
      CHAIN_ENDPOINT: ws://subtensor:9946
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["python", "utils/init_solochain.py"]

  miner_server:
    environment:
      MINER_HOST: ${MINER_HOST}
      MINER_PORT: ${MINER_PORT}
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["python", "model_server/miner_server.py"]

  miner:
    depends_on:
      - miner_server
    environment:
      MNEMONIC_COLDKEY: ${MINER_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${MINER_HOTKEY_MNEMONIC}
      WALLET_NAME: ${MINER_NAME}
      WALLET_HOTKEY: ${MINER_HOTKEY}
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ws://subtensor:9946
      WORKER_TYPE: 'miner'
      MINER_SERVER: http://miner_server:5000
    build:
      context: ..
      dockerfile: Dockerfile

  validator:
    environment:
      MNEMONIC_COLDKEY: ${MINER_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${MINER_HOTKEY_MNEMONIC}
      WALLET_NAME: ${VALIDATOR_NAME}
      WALLET_HOTKEY: ${VALIDATOR_HOTKEY}
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ws://subtensor:9946
      WORKER_TYPE: 'validator'
    depends_on:
      - miner
    build:
      context: ..
      dockerfile: Dockerfile

networks:
  chainnet: