version: '3.8'

services:

  miner_server_openai:
    environment:
      MINER_PORT: ${MINER_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    build:
      context: ..
      dockerfile: Dockerfile
    command: python blackbox_example/miner_server_open_ai.py

  miner:
    depends_on:
      - miner_server_openai
    build:
      context: ..
      args:
        - MNEMONIC_COLDKEY=${MINER_COLDKEY_MNEMONIC}
        - MNEMONIC_HOTKEY=${MINER_HOTKEY_MNEMONIC}
        - WALLET_NAME=MINER_NAME
      dockerfile: Dockerfile
    command: python neurons/miner.py --netuid ${NETWORK_UID} --wallet.name ${MINER_NAME} --wallet.hotkey ${MINER_HOTKEY} --subtensor.network ${NETWORK_TYPE} --logging.debug

  validator:
    depends_on:
      - miner
    build:
      args:
        - MNEMONIC_COLDKEY=${VALIDATOR_COLDKEY_MNEMONIC}
        - MNEMONIC_HOTKEY=${VALIDATOR_HOTKEY_MNEMONIC}
        - WALLET_NAME=VALIDATOR_NAME
      context: ..
      dockerfile: Dockerfile
    command: python neurons/validator.py --netuid ${NETWORK_UID} --wallet.name ${VALIDATOR_NAME} --wallet.hotkey ${VALIDATOR_HOTKEY} --subtensor.network ${NETWORK_TYPE} --logging.debug
