version: '3.8'

services:

  miner_server_openai:
    environment:
      MINER_PORT: ${MINER_PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    build:
      context: ..
      dockerfile: Dockerfile
    command: python blackbox_example/miner_server_open_ai.py

  miner:
    depends_on:
      - miner_server_openai
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      MNEMONIC_COLDKEY: ${MINER_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${MINER_HOTKEY_MNEMONIC}
      WALLET_NAME: ${MINER_NAME}
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ${NETWORK_TYPE}
      WORKER_TYPE: 'miner'

  validator:
    depends_on:
      - miner
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      MNEMONIC_COLDKEY: ${VALIDATOR_COLDKEY_MNEMONIC}
      MNEMONIC_HOTKEY: ${VALIDATOR_HOTKEY_MNEMONIC}
      WALLET_NAME: ${VALIDATOR_NAME}
      NETWORK_UID: ${NETWORK_UID}
      NETWORK_TYPE: ${NETWORK_TYPE}
      WORKER_TYPE: 'validator'
